### ISSUE TITLE
maven repo on googlecode unreachable

### ISSUE THREAD

**Issue by programingjd** [melix/jlangdetect#7]
It was working earlier, but now it seems that 
maven {
    url 'https://jlangdetect.googlecode.com/svn/repo'
}
in build.gradle doesn't work anymore.
Maybe google took down the svn repos for its google code projects?

How about moving the repo to bintray/jcenter?

**Comment by spyluxos** [comment]
These were the original jars: from googlecode
[jlangdetect-0.4.zip](https://github.com/melix/jlangdetect/files/489512/jlangdetect-0.4.zip)

Could Cédric not simply publish them (again) on Maven central or JCenter?

**Comment by buczaq** [comment]
Hello @melix , perhaps you missed this issue. Are you planning to publish these jars again somewhere? One of the projects I wanted to analyze for my master's thesis uses jlangdetect and it would be great to compile it without having to manually download jars from link provided above. Thanks in advance for your answer!

**Comment by melix** [comment]
I have published version 0.6 on Maven Central. This version requires Java 8.
